### ISSUE TITLE
Feature Request: Zootel Templates

### ISSUE THREAD

**Issue by brimwats** [akosbalasko/zoottelkeeper-obsidian-plugin#17]
Zoottelkeeper works with both the original Folder Note and the AidenLX Folder Note Plugins. However, because Zootelkeeper is "faster" than other plugins, it ends up making a note before I can manually make a folder note. 

Do you think there is any way you could add a template feature that is similar to folder note? It wouldn't have to support all of these things, but it would be nice if it could support FOLDER_NAME and FOLDER_PATH like this:

![image](https://user-images.githubusercontent.com/49103046/131256735-2f3cbf23-1cf6-4e90-b70a-f281b43316ef.png)

_Originally posted by @brimwats in https://github.com/akosbalasko/zoottelkeeper-obsidian-plugin/issues/6#issuecomment-907814982_

**Comment by kquinsland** [comment]
I would love to see something like this! I use the super powerful [templater ](https://silentvoid13.github.io/Templater/docs/commands/dynamic-command/)plugin by `silentvoid13` for a lot of things.


The `zoottelkeeper` plugin could leverage the work done in existing template plugins rather than re-invent the wheel. Allow for configuration tweaks to `zoottelkeeper` via the frontmatter of the index file similar to how the [`dynamic-toc`](https://github.com/aidurber/obsidian-plugin-dynamic-toc#code-block) plugin uses the codeblock.

Example:

Let's say that I have my `prefix` set to `000_idx_`. In the `Projects` folder, the `zoottelkeeper` plugin would  generate a `000_idx_Projects.md` file. I would then adjust the content of this file to tweak the way the index file in `Projects` is generated: 

```markdown
---
tags: MOC/Index, MOC/Projects

# Tweak the index file for Projects
zoottelkeeper:
  # Use the https://silentvoid13.github.io/Templater/docs/commands/dynamic-command/
  indexTemplate: templates/projectIndex.tmpl.md
  
  # A list of regex. Any sub dir in Projects that matches will be part of the index
  indexSubDirs:
     - "*"

---

%% After filtering all of the sub dirs in Projects against indexSubDirs, the final list of files/dirs is fed to the file specified in indexTemplate .... %%

```


Moving _most_ settings to the frontmatter of the index file keeps the settings page clean as features are added / the plugin grows and allows for customization per index.

**Comment by brimwats** [comment]
@kquinsland's solution sounds like a good one!

**Comment by akosbalasko** [comment]
Hi @kquinsland , hi @brimwats ,

I added an option to do not regenerate the whole index file, just update a dedicated place (specified by %% placeholders) only and the frontmatter. In this case everything outside from the placeholders can be customized. So I currently don't really see the added value of supporting templates. But it's probably because I misunderstood the concept, could you please enlight it with an other example? 
What do FOLDER_NAME and FOLDER_PATH stand for in the original feat. request?

**Comment by matclab** [comment]
> Hi @kquinsland , hi @brimwats ,
> 
> I added an option to do not regenerate the whole index file, just update a dedicated place (specified by %% placeholders) only and the frontmatter. 

I feel dumb, but I do not see this option in 0.16.2. Could you give me some clue about its name ?

Anyway thank you very much for this nice and already helpful  plugin… !

**Comment by matclab** [comment]
I wonder if it is not a problem of concurrence : several plugins trying to create the file (Note Folder and Zoottelkeeper), but Zoottelkeeper win, and as such the template defined in *Folder Note* is not used. This is why people are asking for templates in zootlekeeper (i.e for the first creation of the file).

**Comment by brimwats** [comment]
well stated @matclab this is 💯% the reason I am

**Comment by kquinsland** [comment]
> Hi @kquinsland , hi @brimwats ,
> 
> I added an option to do not regenerate the whole index file, just update a dedicated place (specified by %% placeholders) only and the frontmatter. In this case everything outside from the placeholders can be customized. So I currently don't really see the added value of supporting templates. But it's probably because I misunderstood the concept, could you please enlight it with an other example? What do FOLDER_NAME and FOLDER_PATH stand for in the original feat. request?


When i typed up that example, i wasn't 100% sure how one plugin could call another. My assumption/hope was that it was possible.

Basically, `zoottelkeeper` would call the templater plugin with two arguments:

- the template file specified in `indexTemplate`
- the list of files/folders that `zoottelkeeper` identified.


This way, the `zoottelkeeper` plugin does not need to care about how the user might want the index to look like... let the template worry about that.

The example i gave above with the template file was more of an idea / wishful thinking. I don't know if obsidian allows for one plugin to interact with another via an API.

**Comment by Tuo-Luo** [comment]
Template file is specified, but the code block does not work.

This is template file.
![This is template file](https://user-images.githubusercontent.com/59633620/209722615-931ef3a8-19f2-4fd8-bbc1-01a867ce864e.png)

This is the wrong result of Zoottelkeeper Template File.
![This is result](https://user-images.githubusercontent.com/59633620/209722627-1662ebdd-9ae1-4020-885d-7748a452ee01.png)

This is the correct result of my direct use of Templater.
![This is the correct result](https://user-images.githubusercontent.com/59633620/209722635-98d5906b-1695-4856-90bb-f4a7f826d17e.png)
