### ISSUE TITLE
Feature Request: Use Emojis to indicate File/Folder/Itemtype

### ISSUE THREAD

**Issue by brimwats** [akosbalasko/zoottelkeeper-obsidian-plugin#23]
It would be awesome if Zoottelkeeper could use emojis on certain things. For example, if there was a folder it might have:

`📂 - [[300 - Research. Projects. Service/STFM - HistClass/_Final/_Final|_Final]]`

A note might get a 📝 and so on. A text box where people could enter comma-seperated filetypes (i.e. `docx, doc, etc) and pick an emoji to show up would be fantastic :D

**Comment by akosbalasko** [comment]
Hi @brimwats , 
Folder/file emoji support is on the road, it can be generalized to support different file types as how you suggested will be done as a next round. 
Thank you for this great idea, I enjoyed implementing this :)

**Comment by akosbalasko** [comment]
released in version 0.16.0

**Comment by claremacrae** [comment]
> released in version 0.16.0

I think there might be a harmless trivial consequence of this change, which seems not to affect the display - but I'll mention it in case it's helpful...

I noticed that there's a space before each index item now - is that intentional?

![2021-09-26_13-10-33](https://user-images.githubusercontent.com/4840096/134807422-b8f979bb-5a8d-4362-87f2-72bfb250e445.png)

**Comment by akosbalasko** [comment]
Hi @claremacrae ,
Yes, I know about it, but I had a feeling that it's okay.

**Comment by claremacrae** [comment]
Hi @akosbalasko - great...

**Comment by brimwats** [comment]
thanks so much!!
