### ISSUE TITLE
Bug: Not generating meta tags or frontmatter section

### ISSUE THREAD

**Issue by leah-ferguson** [akosbalasko/zoottelkeeper-obsidian-plugin#39]
I've indexed my vault for the first time using Zoottelkeeper, and have the Meta Tags enabled in my settings. It successfully generated index notes for each of my folder, and they're auto-updating which is awesome!

However, it isn't generating a frontmatter section in my index notes, and also isn't generating the `tags: index` I have set in the settings.

**Comment by akosbalasko** [comment]
Hi @leah-ferguson ,
thank you for reporting it, it looks like a bug, I'll investigate it.

**Comment by akosbalasko** [comment]
Hi @leah-ferguson  and all,
I think the problem is that the frontmatter separator is missing from the index file. Please place the default separator (--- ) twice below each other in the index file, and the tags property will be updated automatically.

Or, as I'll release a new version in where I introduce the template, you will be able to set a template containing frontmatter separator and anything else as you wish.

**Comment by giocaizzi** [comment]
Hi, I was following because i had the same issue.

Now it's solved. The frontmatter section is create. However, after some time that the plugin gets triggered because of edits in the files of the folder, the file looks like this
<img width="670" alt="Schermata 2021-12-27 alle 12 50 07" src="https://user-images.githubusercontent.com/64302135/147472312-3d270625-dff1-45d9-912e-1b16146385f8.png">
.
