### ISSUE TITLE
MOC duplicate 

### ISSUE THREAD

**Issue by keape** [akosbalasko/zoottelkeeper-obsidian-plugin#47]
In some cases the folder name triggers a MOC duplicate within the same folder. 
i.e. Inside the Science folder creates correctly the file MOC_Science but, after a couple of minutes, creates the file MOC_Science (1) too.
The error must be caused by the denomation of the folder because changing the folder name this error doesn't occur.

**Comment by akosbalasko** [comment]
Hi @keape , thanks for reporting this strange issue, i try to reproduce it.

**Comment by akosbalasko** [comment]
I'm sorry, I was not able to reproduce the problem.

**Comment by maximilianhagerf** [comment]
Can we reopen this, I'm having the same issue since I added Obsidian Sync. 

Seems fairly inconsistent. I have a folder called Family, and I've set up Zoottelkeeper with an empty 'Index Prefix' to create a file index with the same name as the folder, and it just keeps adding a two index files resulting in a Family.md and a Family (1).md.

**Comment by lzilioli** [comment]
I am having this happen a TON on a local vault. Very annoying. +1 to reopen

<img width="342" alt="image" src="https://github.com/akosbalasko/zoottelkeeper-obsidian-plugin/assets/4664956/795534c2-3106-4dd7-addb-547ac829e932">
