### ISSUE TITLE
Only folders created in Obsidian

### ISSUE THREAD

**Issue by gardssh** [akosbalasko/zoottelkeeper-obsidian-plugin#52]
It seems only folders created from inside Obsidian will get an indexing file. Is this by design or a bug? I have a lot of folders I don't made in Obsidian, and none of them get an index file.

**Comment by akosbalasko** [comment]
Hi @gardssh !

By design the index files should be created automatically in those folders, which are touched( made some file manipulations like file creation deletion or move). And please note that the folder must be set in the inclusion settings( or you can leave it empty if you would like to make Zoottelkeeper work on all folders in the vault) .
